/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareafinal;

import MSQL.MetodosSql;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Kisuke Urahara
 */
public class AddProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddProducts
     */
    public AddProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPCategoria = new javax.swing.JTextField();
        txtPMarca = new javax.swing.JTextField();
        txtPNombre = new javax.swing.JTextField();
        txtPCantidad = new javax.swing.JTextField();
        txtPPrecio = new javax.swing.JTextField();
        btnPAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Productos");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Cant Disponible:");

        btnPAgregar.setText("Agregar");
        btnPAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnPAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPAgregar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPAgregarActionPerformed
        MetodosSql metodos = new MetodosSql();
        Productos mod = new Productos();
       
        
        

        if (txtPNombre.getText().equals("") || txtPMarca.getText().equals("")
                || txtPCategoria.getText().equals("")
                || txtPPrecio.getText().equals("") || txtPCantidad.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "HAY CAMPOS VACIOS, FAVOR LLENAR TODOS LOS CAMPOS");
        } else {
            if (metodos.existeProducto(txtPNombre.getText()) == 0) {
                    

                    int c = Integer.parseInt(txtPCantidad.getText());
                    mod.setNombre(txtPNombre.getText());
                    mod.setMarca(txtPMarca.getText());
                    mod.setCategoria(txtPCategoria.getText());
                    mod.setPrecio(txtPPrecio.getText());
                    mod.setCantidad(c);

                    if (metodos.agregar(mod)) {

                        JOptionPane.showMessageDialog(this, "DATOS GUARDADOS CORRECTAMENTE");
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(this, "PRODUCTO NO FUE GUARDADO, FAVOR DE INTENTAR NUEVAMENTE");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "NOMBRE DE PRODUCTO YA EXISTE");
                }
            } 
            
        
    }//GEN-LAST:event_btnPAgregarActionPerformed
    private void limpiar() {
        
        txtPNombre.setText("");
        txtPMarca.setText("");
        txtPCategoria.setText("");
        txtPPrecio.setText("");
        txtPCantidad.setText("");
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtPCantidad;
    public javax.swing.JTextField txtPCategoria;
    public javax.swing.JTextField txtPMarca;
    public javax.swing.JTextField txtPNombre;
    public javax.swing.JTextField txtPPrecio;
    // End of variables declaration//GEN-END:variables
}
